apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shenali-SJ/app-xXZB7BRSWUPPWL2Lz8FUYF-helm.git
    targetRevision: main
    path: ./
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: ""
    namespace: argoapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
